### ISSUE TITLE
Basic JUCE window

### ISSUE THREAD

**Issue by still18** [still18/6106Group4#1]
We all need to work to try and get a basic JUCE window to compile and open. From there, we can explore basic UI elements, and making it run as an executable.

**Comment by med1844** [comment]
Found a good & detailed introduction to the JUCE GUI. [link](https://www.getdunne.net/wiki/doku.php?id=juce_gui_basics)

**Comment by med1844** [comment]
I'm pretty sure that we all can compile basic juce app & see the window, therefore closed.
