### ISSUE TITLE
Plugin Host Review

### ISSUE THREAD

**Issue by still18** [still18/6106Group4#4]
Investigate the plugin in prepare to share by the next SCRUM standup meeting. We need to all be understanding what the possibilities and limitations of it is so we can better prepare the application to account.

**Comment by med1844** [comment]
Just found a [plugin scanner](https://github.com/Tracktion/pluginval) that is also implemented in juce and can be used as reference. Currently it can scan plugins that mine test plugin cannot (e.g. bx_subfilter). More investigation is required.

**Comment by med1844** [comment]
The plugin host can now be eventually loaded and actually take effect.
